// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCalculatorAPI.Data;

#nullable disable

namespace TaxCalculatorAPI.Migrations
{
    [DbContext(typeof(SqliteDataContext))]
    [Migration("20220513091819_CreateUserTable")]
    partial class CreateUserTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.ApiUser", b =>
                {
                    b.Property<int>("ApiUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ApiUserId");

                    b.ToTable("ApiUsers");

                    b.HasData(
                        new
                        {
                            ApiUserId = 1,
                            Email = "admin@testsite.com",
                            Password = "$2a$11$Q9Zs1acAHave4P9ojRGXA.rpbkWuAZGDenboe8fyvKXxQLinn8b5."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
