// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCalculatorAPI.Data;

#nullable disable

namespace TaxCalculatorAPI.Migrations
{
    [DbContext(typeof(SqliteDataContext))]
    [Migration("20220517141646_AddedTaxCalulatorDataModel")]
    partial class AddedTaxCalulatorDataModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.ApiUser", b =>
                {
                    b.Property<int>("ApiUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ApiUserId");

                    b.ToTable("ApiUsers");

                    b.HasData(
                        new
                        {
                            ApiUserId = 1,
                            Email = "admin@testsite.com",
                            Password = "$2a$11$6N1TqM6rPPHxTnt.SSVNOuYrY.k2vbkUNTc2X21ac/Z3HM8vN8dQy"
                        });
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.FlatRateTaxTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RateTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RateValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RateTypeId");

                    b.ToTable("FlatRateTaxTable");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.FlatValueTaxTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinimumValue")
                        .HasColumnType("REAL");

                    b.Property<int>("RateTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RateValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RateTypeId");

                    b.ToTable("FlatValueTaxTable");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.PostalCode", b =>
                {
                    b.Property<int>("PostalCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PostalCodeId");

                    b.ToTable("PostalCode");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.ProgressiveTaxTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaximumValue")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumValue")
                        .HasColumnType("REAL");

                    b.Property<int>("RateTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RateValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RateTypeId");

                    b.ToTable("ProgressiveTaxTable");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.RateType", b =>
                {
                    b.Property<int>("RateTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RateTypeDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RateTypeId");

                    b.ToTable("RateType");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.TaxSubmission", b =>
                {
                    b.Property<int>("TaxSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AnnualIncome")
                        .HasColumnType("REAL");

                    b.Property<double>("CalculatedTax")
                        .HasColumnType("REAL");

                    b.Property<int>("PostalCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("TaxSubmissionId");

                    b.HasIndex("PostalCodeId");

                    b.ToTable("TaxSubmission");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.TaxType", b =>
                {
                    b.Property<int>("TaxTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxTypeDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaxTypeId");

                    b.ToTable("TaxType");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.TaxTypeSelector", b =>
                {
                    b.Property<int>("TaxTypeSelectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostalCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaxTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaxTypeSelectorId");

                    b.HasIndex("PostalCodeId");

                    b.HasIndex("TaxTypeId");

                    b.ToTable("TaxTypeSelector");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.FlatRateTaxTable", b =>
                {
                    b.HasOne("TaxCalculatorAPI.Data.Entities.RateType", "RateType")
                        .WithMany()
                        .HasForeignKey("RateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RateType");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.FlatValueTaxTable", b =>
                {
                    b.HasOne("TaxCalculatorAPI.Data.Entities.RateType", "RateType")
                        .WithMany()
                        .HasForeignKey("RateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RateType");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.ProgressiveTaxTable", b =>
                {
                    b.HasOne("TaxCalculatorAPI.Data.Entities.RateType", "RateType")
                        .WithMany()
                        .HasForeignKey("RateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RateType");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.TaxSubmission", b =>
                {
                    b.HasOne("TaxCalculatorAPI.Data.Entities.PostalCode", "PostalCode")
                        .WithMany("TaxSubmissions")
                        .HasForeignKey("PostalCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostalCode");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.TaxTypeSelector", b =>
                {
                    b.HasOne("TaxCalculatorAPI.Data.Entities.PostalCode", "PostalCode")
                        .WithMany("TaxTypeSelectors")
                        .HasForeignKey("PostalCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxCalculatorAPI.Data.Entities.TaxType", "TaxType")
                        .WithMany("TaxTypeSelectors")
                        .HasForeignKey("TaxTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostalCode");

                    b.Navigation("TaxType");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.PostalCode", b =>
                {
                    b.Navigation("TaxSubmissions");

                    b.Navigation("TaxTypeSelectors");
                });

            modelBuilder.Entity("TaxCalculatorAPI.Data.Entities.TaxType", b =>
                {
                    b.Navigation("TaxTypeSelectors");
                });
#pragma warning restore 612, 618
        }
    }
}
